name: CI - Maven + Selenium

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  tests:
    name: Build & Test (Java ${{ matrix.java }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ '17', '21' ]

    env:
      PROJECT_DIR: ./webdriver-manager
      MAVEN_OPTS: "-Xmx1024m"
      SELENIUM_HTTP_FACTORY: "jdk-http-client"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Show Chrome version (debug)
        run: |
          google-chrome --version || true
          which google-chrome || true

      - name: Build & Test (headless)
        working-directory: ${{ env.PROJECT_DIR }}
        shell: bash
        run: |
          set -e
          CMD="./mvnw"
          if [ ! -x "./mvnw" ]; then
            CMD="mvn"
          fi

          $CMD -B \
            -Dheadless=true \
            -Dwebdriver.http.factory=${SELENIUM_HTTP_FACTORY} \
            test

      - name: Upload Surefire/Failsafe Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-java-${{ matrix.java }}
          path: |
            ${{ env.PROJECT_DIR }}/**/target/surefire-reports/**
            ${{ env.PROJECT_DIR }}/**/target/failsafe-reports/**
          if-no-files-found: ignore

      - name: Upload Screenshots/Logs (se existirem)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-java-${{ matrix.java }}
          path: |
            ${{ env.PROJECT_DIR }}/**/target/screenshots/**
            ${{ env.PROJECT_DIR }}/**/target/*.log
            ${{ env.PROJECT_DIR }}/**/logs/**
          if-no-files-found: ignore
